```{r}
getwd()
list.files()
pf <- read.csv('pseudo_facebook.tsv', sep = '\t')
names(pf)
```


```{r}
library('ggplot2')
qplot(x = dob_day, data = pf) +
  scale_x_discrete(breaks = 1:31)


```
```{r}
#install.packages('ggthemes', dependencies = TRUE) 
library(ggthemes) 
```

```{r}
ggplot(aes(x = dob_day), data = pf) + 
  geom_histogram() + 
  scale_x_discrete(breaks = 1:31)

```
```{r}
ggplot(aes(x = dob_day), data = pf) + 
  geom_histogram() + 
  scale_x_discrete(breaks = 1:31) +
  facet_wrap(~dob_month,ncol = 3)
```
```{r}
summary(pf)
names(pf)
```

```{r}
ggplot(aes(x = friend_count), data = pf) + 
  geom_histogram()  
  #+ scale_x_discrete(breaks = 1:31) +
  #facet_wrap(~dob_month,ncol = 3)
```

```{r}
ggplot(aes(x = friend_count), data = pf) + 
  geom_histogram() + 
  scale_x_continuous(limits = c(0, 1000))
```
```{r}
ggplot(aes(x = friend_count), data = pf) + 
  geom_histogram(binwidth = 25) + 
  scale_x_continuous(limits = c(0, 1000), breaks = seq(0, 1000, 50))
```

```{r}
qplot(x = friend_count, data = pf, binwidth = 25) + 
  scale_x_continuous(limits = c(0, 1000), breaks = seq(0, 1000, 50)) +
  facet_wrap(~gender)
```
```{r}
ggplot(aes(x = friend_count), data = subset(pf, !is.na(gender))) + 
  geom_histogram() + 
  scale_x_continuous(limits = c(0, 1000), breaks = seq(0, 1000, 50)) + 
  facet_wrap(~gender)
```

```{r}
table(pf$gender)
```
```{r}
by(pf$friend_count, pf$gender, summary)
```
```{r}
ggplot(aes(x = tenure), data = pf) + 
   geom_histogram(binwidth = 30, color = 'black', fill = '#099DD9')
```

```{r}
ggplot(aes(x = tenure/365), data = pf) + 
   geom_histogram(binwidth = 1, color = 'black', fill = '#099DD9')
```
```{r}
#instructor ggplot solution see notes for qplot solution
ggplot(aes(x = tenure/365), data = pf) + 
   geom_histogram(binwidth = .25, color = 'black', fill = '#F79420')
```


```{r}
#I set a new scale to zoom in on the data
ggplot(aes(x = tenure/365), data = pf) + 
   geom_histogram(binwidth = .25, color = 'black', fill = '#F79420') + 
   scale_x_continuous(limits = c(0, 7), breaks = seq(1,7,1))
```
```{r}
#add labels
ggplot(aes(x = tenure / 365), data = pf) + 
  geom_histogram(binwidth = .25,color = 'black', fill = '#F79420') + 
  scale_x_continuous(breaks = seq(1, 7, 1), limits = c(0, 7)) + 
  xlab('Number of years using Facebook') + 
  ylab('Number of users in sample')
```
```{r}
#quiz to create a histogram of ages and play with data
#what names do we have to work with?
names(pf)
summary(pf$age)
#now to create a histogram of ages
ggplot(aes(x = age), data = pf) + 
  geom_histogram(binwidth = 1,color = 'black', fill = '#F79420') + 
  xlab('Age') + 
  ylab('Frequency')
#hmm, the upper extremes strain credulity
  
```

```{r}
#let's split this up a bit
ggplot(aes(x = age), data = pf) + 
  geom_histogram(binwidth = 5,color = 'black', fill = '#F79420') + 
  scale_x_continuous(breaks = seq(5, 110, 5), limits = c(10, 110)) +
  xlab('Age') + 
  ylab('Frequency')
```

```{r}
#let's look at that upper range
ggplot(aes(x = age), data = pf) + 
  geom_histogram(binwidth = 10,color = 'black', fill = '#F79420') + 
  scale_x_continuous(breaks = seq(10, 110, 10), limits = c(90, 110)) +
  xlab('Age') + 
  ylab('Frequency')
```
```{r}
#install.packages('gridExtra') 
library(gridExtra) 
```

```{r}
#create 1 column with 3 histograms: friend count, log10 friend count, sqrt friend #count

p1 = ggplot(aes(x = friend_count), data = pf) + 
  geom_histogram(binwidth = 25, fill = '#F79420') + 
  scale_x_continuous(limits = c(0, 1000), breaks = seq(0, 1000, 50))

p2 = ggplot(aes(x = friend_count), data = pf) + 
  geom_histogram(fill = '#F79420') + 
  scale_x_log10() +
  xlab('log10(friend_count)')

p3 = ggplot(aes(x = friend_count), data = pf) + 
  geom_histogram(fill = '#F79420') + 
  scale_x_sqrt() +
  xlab('sqrt(friend_count)')


# arrange plots in grid
grid.arrange(p1, p2, p3, ncol=1)
```


