---
title: "Lesson4_problemset"
output: html_document
---

```{r 'setwd'}
setwd("~/Udacity/dataAnalysisR/EDA_R_Udacity/lesson4")
```
###Load Library and Data Sets###

```{r 'load libs,data'}
library(ggplot2)
library(gridExtra)
library(dplyr)
library('alr3')
library(dplyr)
getwd()
list.files()
data(diamonds)
summary(diamonds)
names(diamonds)
```

```{r scatterplot price vs. x}
ggplot(aes(x = x , y = price), data = diamonds ) +
  geom_point(color = 'orange')

```
```{r correlation of price}
cor.test(diamonds$x, diamonds$price)
cor.test(diamonds$y,diamonds$price)
cor.test(diamonds$z, diamonds$price)

```
```{r price vs. depth}
ggplot(aes(x = depth, y = price), data = diamonds) +
  geom_point(color = 'red')
```

```{r adjustments price vs. depth}
ggplot(aes(x = depth, y = price), data = diamonds) +
  geom_point(alpha = .01, color = 'red') +
  scale_x_continuous(breaks = seq(40,80,2))
```

```{r correlation depth vs. price}
cor.test(diamonds$depth, diamonds$price)
```

```{r price vs. carat}
ggplot(aes(x = carat, y = price,), data = diamonds)+
  geom_point(color = 'blue') +
  xlim(0, quantile(diamonds$carat,0.99)) +
  ylim(0, quantile(diamonds$price,0.99))
```
```{r price vs. volume}
volume = diamonds$x * diamonds$y * diamonds$z
ggplot(aes(x = volume, y = price), data = diamonds) +
  geom_point(color = 'green')
```
```{r correlations on subsets}
diamonds$volume = volume
volume_subset = subset(diamonds, diamonds$volume > 0 & diamonds$volume <=800)
cor.test(volume_subset$volume, volume_subset$price)
```


```{r adjustments price vs. volume}
ggplot(aes(x = volume, y = price), data = volume_subset) +
  geom_point(color = 'green') +
  geom_smooth()
```

```{r mean price by clarity}
# Use the function dplyr package
# to create a new data frame containing
# info on diamonds by clarity.

# Name the data frame diamondsByClarity

# The data frame should contain the following
# variables in this order.

#       (1) mean_price
#       (2) median_price
#       (3) min_price
#       (4) max_price
#       (5) n

# where n is the number of diamonds in each
# level of clarity.

diamondsByClarity <- diamonds %>%
  group_by(clarity) %>%
  summarise(mean_price = mean(price),
            median_price = median(as.numeric(price)),#necessary due to bug in version 0.4.1 yesterday (2015-01-14)
            min_price = min(price),
            max_price = max(price),
            n = n()) %>%
  arrange(clarity)

diamondsByClarity

```

```{r two bar plots}
#create data sets
diamonds_by_clarity <- group_by(diamonds, clarity)
diamonds_mp_by_clarity <- summarise(diamonds_by_clarity, mean_price = mean(price))

diamonds_by_color <- group_by(diamonds, color)
diamonds_mp_by_color <- summarise(diamonds_by_color, mean_price = mean(price))

#create plots
p1 = ggplot(aes(x = clarity, y = price), data = diamonds) +
  geom_bar(stat = 'identity', aes(fill = clarity))

p2 = ggplot(aes(x = color, y = price), data = diamonds) +
  geom_bar(stat = 'identity', aes(fill = color))

grid.arrange(p1,p2,ncol = 1)
```

