---
title: "Udacity EDA R Final Project"
author: "Andrew Thomas Bauman"
date: "Tuesday, February 10, 2015"
output: html_document
---

#Introduction#


```{r setpath}
setwd("~/Udacity/dataAnalysisR/EDA_R_Udacity/EDA_R_FinalProject")
```

```{r load libraries}
library(RSocrata) #to access socrata data
library(ggplot2)
library(gridExtra)
library(dplyr)
library(alr3)
library(GGally)
library(reshape2)
library(acs) #to access census data
library(tidyr) #bare bones data tidying library
#test

```

other data sets for vaccination



```{r load school vaccination exemption data sets}

#2013-2014 vaccination exemption data set, aka kingcounty.gov data set 1
kcounty_k12_vaccexempt_2013to2014 <- read.socrata('https://data.kingcounty.gov/dataset/Vaccination-Exemptions-in-King-County/xs83-3zit')

#kingcounty.gov data set 2
 kcounty_immcoverage_k12_mostrecent_2014<- read.socrata('https://data.kingcounty.gov/dataset/K-12-Immunization-Coverage-by-Most-Recent-School-R/h2ef-byuh')

#kingcounty.gov data set 3
kcounty_k_mostrecent_2014 <- read.socrata('https://data.kingcounty.gov/dataset/Kindergarten-Immunization-Coverage-by-Most-Recent-/agib-e23h')

#WA DOH SY 2011-2012 K12
doh_K12_2011to2012 <- read.csv('~/Udacity/dataAnalysisR/EDA_R_Udacity/EDA_R_FinalProject/data/WA_Vacc_K12_2011.csv')

#WA DOH SY 2012-2013 K12
doh_k12_2012to2013 <- read.csv('~/Udacity/dataAnalysisR/EDA_R_Udacity/EDA_R_FinalProject/data/WA_Vacc_K12_2012.csv')

#WA doh SY 2013-2014 K12
doh_k12_2013to2014 <- read.csv('~/Udacity/dataAnalysisR/EDA_R_Udacity/EDA_R_FinalProject/data/WA_Vacc_K12_2013.csv')
```

```{r data structures and names}
kcounty_immcoverage_k12_mostrecent_2014_names <- names(kcounty_immcoverage_k12_mostrecent_2014)
kcounty_k_mostrecent_2014 <- names(kcounty_k_mostrecent_2014)
kcounty_k12_vaccexempt_2013to2014_names <- names(kcounty_k12_vaccexempt_2013to2014)
doh_K12_2011to2012_names <- names(doh_K12_2011to2012)
doh_k12_2012to2013_names <- names(doh_k12_2012to2013)
doh_k12_2013to2014_names <- names(doh_k12_2013to2014)

#kingcounty.gov name sets
kcounty_immcoverage_k12_mostrecent_2014_names
kcounty_k_mostrecent_2014
kcounty_k12_vaccexempt_2013to2014_names

#WA DOH name sets
vaccexempt_st_fyi_2011_names
doh_k12_2012to2013_names
doh_k12_2013to2014
doh_k12_2013to2014_names
```

