---
title: "Lesson 5 Problem Set"
output: html_document
---

```{r load libraries}

library(ggplot2)
library(gridExtra)
library(dplyr)
library('alr3')
library("GGally")
library('reshape2')
```

```{r load data}
data(diamonds)
summary(diamonds)
names(diamonds)
```


```{r histogram diamond prices faceted by color}

# Create a histogram of diamond prices.
# Facet the histogram by diamond color
# and use cut to color the histogram bars.

ggplot(data = diamonds, aes(x = price)) +
  geom_histogram(aes(fill = cut))  +
  scale_x_log10() + #data is long-tailed
  facet_wrap(~color) 
  #scale_fill_brewer(type = 'qual') is an option per instructor notes but I don't like the colors

```

```{r scatterplot price vs. table color by cut}
# Create a scatterplot of diamond price vs.
# table and color the points by the cut of
# the diamond.

ggplot(data = diamonds, aes(x = table, y = price)) +
geom_point(aes(color = cut)) +
scale_colour_brewer(type = 'qual') +
scale_x_continuous(limits = c(50,80), breaks = seq(50,80,2))
```


```{r scatterplot price vs ~ volume, color by clarity}
# Create a scatterplot of diamond price vs.
# volume (x * y * z) and color the points by
# the clarity of diamonds. Use scale on the y-axis
# to take the log10 of price. You should also
# omit the top 1% of diamond volumes from the plot.

# Note: Volume is a very rough approximation of
# a diamond's actual volume.

# The plot should look something like this.
# http://i.imgur.com/excUpea.jpg

# Note: In the link, a color palette of type
# 'div' was used to color the scatterplot using
# scale_color_brewer(type = 'div')

diamonds$volume = diamonds$x * diamonds$y * diamonds$z

ggplot(data = diamonds, aes(x = volume, y = price)) +
  geom_point(aes(color = clarity)) +
  xlab('Volume') +
  scale_x_continuous(limits = c(0,1000), breaks = seq(0,100,100)) +
  scale_color_brewer(type = 'div')

# not really liking the spread and it doesn't look like example plot

ggplot(aes(x = x*y*z, y = price), data = diamonds) +
  geom_point(aes(color = clarity)) +
  xlab('Volume') +
  scale_y_log10() + 
  coord_cartesian(xlim = c(0, quantile(diamonds$volume, 0.99))) +
  scale_color_brewer(type = "div")
```


```{r proportion of friendships initiated}

# Many interesting variables are derived from two or more others.
# For example, we might wonder how much of a person's network on
# a service like Facebook the user actively initiated. Two users
# with the same degree (or number of friends) might be very
# different if one initiated most of those connections on the
# service, while the other initiated very few. So it could be
# useful to consider this proportion of existing friendships that
# the user initiated. This might be a good predictor of how active
# a user is compared with their peers, or other traits, such as
# personality (i.e., is this person an extrovert?).

# Your task is to create a new variable called 'prop_initiated'
# in the Pseudo-Facebook data set. The variable should contain
# the proportion of friendships that the user initiated.

# This programming assignment WILL BE automatically graded.

# DO NOT DELETE THIS NEXT LINE OF CODE
# ========================================================================
pf <- read.delim('C:/Users/Andrew/Documents/Udacity/dataAnalysisR/EDA_R_Udacity/lesson3/pseudo_facebook.tsv')



# ENTER YOUR CODE BELOW THIS LINE
# ========================================================================
pf$prop_initiated = pf$friendships_initiated/pf$friend_count

#code suggested by instructor

#pf <- transform(pf, prop_initiated = friendships_initiated/friend_count ) 

#dplyr solution add suppressMessages(library(dplyr)) to make it pass grader

#pf<- pf %>% 
#     mutate(prop_initiated = friendships_initiated / friend_count)

```

```{r prop initiated vs tenure}
# Create a line graph of the proportion of
# friendships initiated ('prop_initiated') vs.
# tenure and color the line segment by
# year_joined.bucket.

# Recall, we created year_joined.bucket in Lesson 5
# by first creating year_joined from the variable tenure.
# Then, we used the cut function on year_joined to create
# four bins or cohorts of users.

# (2004, 2009]
# (2009, 2011]
# (2011, 2012]
# (2012, 2014]

# The plot should look something like this.
# http://i.imgur.com/vNjPtDh.jpg
# OR this
# http://i.imgur.com/IBN1ufQ.jpg

# This assignment is not graded and
# will be marked as correct when you submit.

# ENTER YOUR CODE BELOW THIS LINE
# ===========================================================
pf$year_joined <- floor(2014 - pf$tenure/365)
pf$year_joined.bucket <- cut(pf$year_joined, c(2004,2009,2011,2012,2014))
table(pf$year_joined.bucket)

ggplot(aes(x = tenure, y = prop_initiated), 
              data = subset(pf, !is.na(pf$year_joined))) + 
  geom_line(aes(color = year_joined.bucket), stat = 'summary', fun.y = median)

#smooth the data
pf$year_joined <- floor(2014 - pf$tenure/365)
pf$year_joined.bucket <- cut(pf$year_joined, c(2004,2009,2011,2012,2014))
table(pf$year_joined.bucket)



ggplot(aes(x = tenure, y = prop_initiated), 
              data = subset(pf, !is.na(pf$year_joined))) + 
  geom_line(aes(color = year_joined.bucket), stat = 'summary', fun.y = median) +
  geom_smooth()

ggplot(aes(x = tenure, y = prop_initiated), 
              data = subset(pf, !is.na(pf$year_joined))) + 
  geom_smooth(aes(color = year_joined.bucket))
```

```{r mean of highest poportion of friendships initiated}

#from plot the higest group appears to be 2012 - 2014

propnum = subset(pf, !is.na(pf$prop_initiated)) 

by(propnum$prop_initiated, propnum$year_joined.bucket, mean)

```

```{r Price/Carat Binned, Faceted, & Colored}

# Create a scatter plot of the price/carat ratio
# of diamonds. The variable x should be
# assigned to cut. The points should be colored
# by diamond color, and the plot should be
# faceted by clarity.

# The plot should look something like this.
# http://i.imgur.com/YzbWkHT.jpg.

# Note: In the link, a color palette of type
# 'div' was used to color the histogram using
# scale_color_brewer(type = 'div')

# This assignment is not graded and
# will be marked as correct when you submit.

# ENTER YOUR CODE BELOW THIS LINE
# ===========================================
ggplot(data = diamonds, aes(x = cut, y = price/carat)) +
  geom_point(aes(color = color), position = position_jitter(width = 0.4)) +
  facet_wrap(~clarity) +
  scale_color_brewer(type = "div")
```

```{r again with the gapminder data}
# The Gapminder website contains over 500 data sets with information about
# the world's population. Your task is to continue the investigation you did at the
# end of Problem Set 4 or you can start fresh and choose a different
# data set from Gapminder.

# If you're feeling adventurous or want to try some data munging see if you can
# find a data set or scrape one from the web.

# In your investigation, examine 3 or more variables and create 2-5 plots that make
# use of the techniques from Lesson 5.

# You can find a link to the Gapminder website in the Instructor Notes.

# Once you've completed your investigation, create a post in the discussions that includes:
#       1. the variable(s) you investigated, your observations, and any summary statistics
#       2. snippets of code that created the plots
#       3. links to the images of your plots

# Copy and paste all of the code that you used for
# your investigation, and submit it when you are ready.
# ================================================================================



```

